# fly.toml app configuration file generated for cosmemo on 2025-09-21T09:59:31+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cosmemo'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  # App
  APP_ENV = 'production'
  APP_URL = 'https://cosmemo.fly.dev'
  ASSET_URL = 'https://cosmemo.fly.dev'

  # Locale
  APP_LOCALE = 'ja'
  APP_FALLBACK_LOCALE = 'ja'
  APP_FAKER_LOCALE = 'ja_JP'

  # Database
  DB_CONNECTION = 'pgsql'

  # Session
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

  # Cache / Queue
  CACHE_STORE = 'file'
  QUEUE_CONNECTION = 'sync'

  # Mail
  MAIL_MAILER = 'smtp'
  MAIL_HOST = 'smtp.gmail.com'
  MAIL_PORT = '587'
  MAIL_ENCRYPTION = 'tls'
  MAIL_FROM_NAME = 'CosMemo'

  # Logging
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
